alias cls=clear
alias showhosts="cat /etc/hosts"
alias ll="ls -lah"
alias ss="./script/server start"
alias sc="./script/console"
alias as="autospec"
alias svn_rm_?="svn stat | grep '^\?' | awk '{print $2}' | xargs rm -rf"
alias svn_r="svn stat | grep '^[MAD]' | awk '{print $2}' | xargs svn revert"
alias ec="/Applications/eclipse/eclipse&"
alias lsip="ipconfig | ruby -e 'puts ARGF.read.scan(/\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/).sort.uniq.reject {|x| x.include?(\"255\")'}"
alias ipconfig=ifconfig
alias svn_ds="svn stat | svn diff | diffstat"
alias git-serve="git daemon --export-all --base-path=/Users/ddeaguiar/Sites/git --detach"
alias grits=git
alias git-rollback="git reset --hard HEAD"
alias catless="cat $1 | less"
alias qgit="/Users/ddeaguiar/bin/qgit.app/Contents/MacOS/qgit"
alias ..="cd .."
alias ...="cd ../.."
alias realias="source ~/.bash_aliases & .bash_aliases_private"
alias log="git log --color"
alias arc="pushd `pwd` && cd ~/lib/arc0 && mzscheme -m -f as.scm && popd"
alias truncate="cp /dev/null"
alias ...='cd ../..'
alias m='mate .'
alias actl="sudo apachectl -k restart"
alias rs='rake spec'
alias git-add-rm='git add . && git st | grep [d]eleted | awk '\''{print $3}'\'' | xargs git rm'
alias gp='git push pu master'
alias ctags="/opt/local/bin/ctags"
alias deploy="rake deploy"
alias e="emacs ."
alias flushdns="dscacheutil -flushcache"
alias gi="sudo gem install"
alias gu="sudo gem update"
alias lll="ls -la | less"
alias myhosts="dscl localhost -list /Local/Default/Hosts"
alias rf="rm -rf"
alias lshosts="cat /etc/hosts"
alias v="vim ."

